# Generated by Django 5.0.3 on 2024-03-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre')),
                ('company', models.CharField(max_length=50, verbose_name='Compañia')),
                ('release_date', models.DateField()),
            ],
            options={
                'db_table': 'videogames',
            },
        ),
    ]
